#+TITLE: Implementation of  College Cloud Edition 
#+AUTHOR: VLEAD
#+SETUPFILE: ../../org-templates/level-2.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document describes steps for syncthing installation on
  Ubuntu-16.04.

** What is =syncthing=?
   It is a Client-Server file synchronization tool for cross
  platforms. A Client will upload new files in a specified local
  directory, using synchthing these files,automatically get
  synchronized to the central server.

* Install =Syncthing= on Ubuntu16.04 machine (VLEAD-Server)
** Install package from PPA
   Add the release PGP keys:
   #+BEGIN_EXAMPLE
   $ curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
   #+END_EXAMPLE
   Add the "release" channel to your APT sources:
   #+BEGIN_EXAMPLE
   $ echo "deb http://apt.syncthing.net/ syncthing release" | sudo tee /etc/apt/sources.list.d/syncthing.list
   #+END_EXAMPLE
** Update and install =syncthing=
   #+BEGIN_EXAMPLE
   $ sudo apt-get update && sudo apt-get install syncthing
   #+END_EXAMPLE
** Enable and start with systemd on server =(VLEAD-Server)=
   #+BEGIN_EXAMPLE
   $ sudo systemctl enable syncthing@$USER.service
   $ sudo systemctl start syncthing@$USER.service
   #+END_EXAMPLE
** Run =syncthing= application 
 - Complete all of the above steps on your system.
 - The application is now installed, but there are a few more things we need to do before it will be ready to use.
 - Now, run the following command to run the syncthing for the first time.
   #+BEGIN_EXAMPLE
   $ syncthing
   #+END_EXAMPLE
   The syncthing process is not a daemon, which means that it runs in
   the current shell session (we will get around this by implementing
   an Upstart script momentarily). It will start the process and
   create some necessary files.

After a moment, you will see an informational message about your Node
ID that looks like this:
#+BEGIN_EXAMPLE
[2EQK3] 15:47:15 OK: Ready to synchronize default (read-write)
[2EQK3] 15:47:15 INFO: Node 2EQK3ZR77PTBQGM44KE7VQIQG7ICXJDEOK34TO3SWOVMUL4QFBHA is "server1" at [dynamic]
#+END_EXAMPLE
When you see this, it means that the process has initialized correctly. We can now stop the process by typing
#+BEGIN_EXAMPLE
CTRL-C
#+END_EXAMPLE
This will stop the process and give us control over the terminal again.
** Configure =syncthing=
  Edit the following configuration file that was created. Open the file in your text editor
#+BEGIN_EXAMPLE
$ sudo vim ~/.config/syncthing/config.xml
#+END_EXAMPLE
Look for a section that deals with the GUI. It should look like this
#+BEGIN_EXAMPLE
<gui enabled="true" tls="false">
    <address>127.0.0.1:8384</address>
</gui>
#+END_EXAMPLE
In the <address> field, change 127.0.0.1:8384 to 0.0.0.0:8384. So, your config.xml will look like below
#+BEGIN_EXAMPLE
<gui enabled="true" tls="false">
    <address>0.0.0.0:8384</address>
</gui>
#+END_EXAMPLE
Save and close the file.
** Access the WebGUI 
    :PROPERTIES:
    :CUSTOM_ID: webgui
    :END:      
   - Open your browser and log into your system, Syncthing interfaces
     by
   visiting their public IP addresses and port 8080
     #+BEGIN_EXAMPLE
     http://<College-cloud-server-IP>:8384
     #+END_EXAMPLE








